/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SunnyMilkFuzzer */

#ifndef _Included_SunnyMilkFuzzer
#define _Included_SunnyMilkFuzzer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SunnyMilkFuzzer
 * Method:    PrintCoverage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SunnyMilkFuzzer_PrintCoverage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
